### ISSUE TITLE
publish to npm, install in separate app with library build

### ISSUE THREAD

**Issue by brietsparks** [jdmg94/minimum-parcel-lib#1]
I might be misunderstanding the goal of this repo, but I am trying to use parcel to bundle a library as an npm package. I cloned this repo and published it to my npm account, then installed it in another app, and do not see any bundled dist files. Is minimum-parcel-lib supposed to be demonstrating this sort of thing or am I mistaken?

**Comment by mauriciord** [comment]
the example is not using React :/
